#!/bin/bash
musicDir="$HOME/Music" # path of music directory, use full path, use $HOME instead of ~
[ -z "$1" ] && echo "No directory given. Exiting." && exit 1

function sort {
	file="$1"
	opt="$2"

	trackNum="$(mediainfo --Inform="General;%Track/Position%" "$file")"
	[ ${#trackNum} == 1 ] && trackNum="0$trackNum"

	title="$(mediainfo --Inform="General;%Title%" "$file")"

	albumArtist="$(mediainfo --Inform="General;%Album/Performer%" "$file")"
	artist="$(mediainfo --Inform="General;%Performer%" "$file")"
	[ -z "$albumArtist" ] && albumArtist="$artist"

	album="$(mediainfo --Inform="General;%Album%" "$file")"

	year=$(mediainfo --Inform="General;%Released_Date%" "$file")
	[ -z "$year" ] && year=$(mediainfo --Inform="General;%Recorded_Date%" "$file")
	year=$(echo "$year" | grep -oE "[0-9]{4}")

	[ ! -d "$musicDir/$artist" ] && [ "$opt" != "-n" ] && mkdir -pv "$musicDir/$artist"
	[ ! -d "$musicDir/$artist/($year) $album" ] && [ "$opt" != "-n" ] && mkdir -pv "$musicDir/$artist/($year) $album"

	filename="$(basename "$file")"
	ext="${filename##*.}"

	newFilename=""
	[ "$trackNum" ] && newFilename+="$trackNum. "
	newFilename+="$albumArtist - $title.$ext"

	[ "$opt" == "-c" ] && cp "$file" "$musicDir/$albumArtist/($year) $album/$newFilename"
	[  "$opt" == "-n" ] && echo "$file -> $musicDir/$albumArtist/($year) $album/$newFilename"
	[ -z "$opt" ] && mv -v "$file" "$musicDir/$albumArtist/($year) $album/$newFilename"
}

# if argument if regular file
if [ -f "$1" ]; then
	sort "$1" "$2"
	exit
fi

file=$(find "$1" \( -name "*.mp3" -o -name "*.flac" -o -name "*.m4a" \) | head -n1)
artist=$(mediainfo --Inform="General;%Performer%" "$file")
album="$(mediainfo --Inform="General;%Album%" "$file")"
albumArtist="$(mediainfo --Inform="General;%Album/Performer%" "$file")"
year=$(mediainfo --Inform="General;%Recorded_Date%" "$file")
[ -z "$year" ] && year=$(mediainfo --Inform="General;%Released_Date%" "$file")
year=$(echo "$year" | grep -oE "[0-9]{4}")

echo -e "
Artist: $artist
Album Artist: $albumArtist
Album: $album
Year: $year\n"

read -p "Are these tags ok? [y/n] " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]
then
    easytag .
fi

# else, if argument is directory
echo "-- Music files --"
find "$1" \( -name "*.mp3" -o -name "*.flac" -o -name "*.m4a" \) -print0 | while read -r -d $'\0' file
do
	sort "$file" "$2"
done

echo -e "\n-- Cover art --"
find "$1" \( -name "*.jpg" -o -name "*jpeg" -o -name "*.png" \) -print0 | while read -r -d $'\0' file
do
	filename="$(basename "$file")"
	ext="${filename##*.}"
	[ "$2" == "-n" ] && echo "$file -> $musicDir/$artist/($year) $album/$filename"
	[ -z "$2" ] && mv -v "$file" "$musicDir/$artist/($year) $album/$filename"
done
